baseURL = "https://www.charisseysabel.com/"
languageCode = "en-us"
title = "Charisse Writes"
theme = "ananke"
[params]
      custom_css = ["css/index.css"]
      featured_image = "/images/atlantic.JPG"
